CREATE DATABASE IF NOT EXISTS bucketlist_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_swedish_ci;

USE bucketlist_db;

CREATE TABLE IF NOT EXISTS bucket_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  priority TINYINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
